[Dialogs]
UserInfo=0
FeatureInfo1=1
SingleDirectory=1
InstallationType=0
FeatureTree=0
License=0
License2=1
NICertificate=0
WinFastStartup=1
ConfirmStart=1
End=1

[Distribution]
Title=1
GUID={4FDEC152-4E0E-4F31-9258-4CC26E7012B3}
PackageGUID={69B55F36-51DA-4023-A76F-07BF5DE4E537}
Version=1.0.1
IDPath=nidist.id
Has64bitPart=1

[EndDialog]
Readme=5;30,50,330,150;static

[Files]
License2TextFile0009=NI;license\NI Released License Agreement - English.rtf
License2TextFile0010=NI;license\NI Released License Agreement - Spanish.rtf
License2TextFile0016=NI;license\NI Released License Agreement - Italian.rtf
License2TextFile0007=NI;license\NI Released License Agreement - German.rtf
License2TextFile0012=NI;license\NI Released License Agreement - French.rtf
License2TextFile0017=NI;license\NI Released License Agreement - Japanese.rtf
License2TextFile0018=NI;license\NI Released License Agreement - Korean.rtf
License2TextFile2052=NI;license\NI Released License Agreement - Simplified Chinese.rtf

[Graphics]
TopBar=IDB_TOPSTRIP,IDB_LARGETOPSTRIP
FullScreen=IDB_FULLSCREEN,IDB_LARGEFULLSCREEN

[InitProgress]
left=55
top=165
right=340
bottom=179
red=206
green=203
blue=173

[InstallLevels]
Default=100

[Localization]
Languages=9
ForceLanguage=9
CustomRes0009=supportfiles\customResource0009.dll
StandardLangXfm0007=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0007.mst
StandardLangXfm0012=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0012.mst
StandardLangXfm0017=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0017.mst
StandardLangXfm0018=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0018.mst
StandardLangXfm2052=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans2052.mst

[Merged]
Path=supportfiles\merged.cab

[OS]
VersionNTMin=10,0,14393,0,0
VersionNTMax=

[Settings]
WelcomeAutoAdvance=1

[SingleDirectoryDialog]
DirText1=4
DirText2=7
Dir1=INSTALLDIR.MDF100
Dir1EditLabel=8
Dir2=NIDIR64
Dir2EditLabel=9

[WinFastStartupDialog]
CheckboxDefaultState=1

[Strings]
WelcomeTitle=2;15,20,260,45
WelcomeText=3;15,55,260,115

[Utilities]

[Parts]
LV2024runtime.msi=
LV2024rtdnet.msi=
activex.msi=
activex64.msi=
nicurl.msi=
nicurl64.msi=
dep_framework64.msi=
ni_error_report64.msi=
NIER_Interface.msi=
NIER_Interface64.msi=
nier_native_installer_64.msi=
LVRT_NBFifo64_2024.msi=
logos.msi=
logos64.msi=
NIWebServer_LVRTE64.msi=
MatlabInterface.msi=
MatlabInterface64.msi=
MDFSupport.msi=
mDNSResponder.msi=
mDNSResponder_W64.msi=
MetaUninstaller.msi=
mkl.msi=
mkl64.msi=
mkl.msi<2>=
mkl64.msi<2>=
MSIProperties.msi=
MSIProperties64.msi=
MStudioCW3DGraph.msi=
VCRTCore.msi=
VCRTWrapper32.msi=
VCRTWrapper64.msi=
PythonInterface.msi=
PythonInterface64.msi=
nisvcloc.msi=
NISysLogUtils.msi=
tdms.msi=
tdms64.msi=
NITraceEngine.msi=
NITraceEngine64.msi=
openssl_ni_3.msi=
openssl_ni_3_x86.msi=
DotNet480.msi=
DotNet480_Wrapper.msi=
error_reporting_common.msi=
LogosXT.msi=
LogosXT64.msi=
niauth.msi=
niauth64.msi=
NI_SysStatePub.msi=
NI_SysStatePub64.msi=
ssl_LV64RTEsupp.msi=
EULADepot2.msi=
KillBit.msi=
KillBit64.msi=
dotnetDesktopRuntimeCore.msi=
ni_ssl.msi=
ni_ssl64.msi=
install.msi=
[LV2024runtime.msi]
Path=bin\p33\LV2024runtime.msi
Volume=1
ProductCode={921BCFD6-48CA-475B-8E03-7C3F1A10B939}
ProductId={921BCFD6-48CA-475B-8E03-7C3F1A10B939}
LangXfm0007=bin\p33\LV2024runtime_deu.mst
LangXfm0012=bin\p33\LV2024runtime_fra.mst
LangXfm0017=bin\p33\LV2024runtime_jpn.mst
LangXfm0018=bin\p33\LV2024runtime_kor.mst
LangXfm2052=bin\p33\LV2024runtime_chs.mst
[LV2024rtdnet.msi]
Path=bin\p33\LV2024rtdnet.msi
Volume=1
ProductCode={56A35654-5D47-4A2A-BD0E-F71FECE9FFC4}
[activex.msi]
Path=bin\p18\activex.msi
Volume=1
ProductCode={EB6C9E35-CBA2-4C2B-8958-55EA6F0EA707}
ProductId={EB6C9E35-CBA2-4C2B-8958-55EA6F0EA707}
LangXfm0007=bin\p18\activex_deu.mst
LangXfm0012=bin\p18\activex_fra.mst
LangXfm0017=bin\p18\activex_jpn.mst
LangXfm0018=bin\p18\activex_kor.mst
LangXfm2052=bin\p18\activex_chs.mst
[activex64.msi]
Path=bin\p18\activex64.msi
Volume=1
ProductCode={52E7C292-9986-4E2F-9273-7F180451D403}
LangXfm0007=bin\p18\activex64_deu.mst
LangXfm0012=bin\p18\activex64_fra.mst
LangXfm0017=bin\p18\activex64_jpn.mst
LangXfm0018=bin\p18\activex64_kor.mst
LangXfm2052=bin\p18\activex64_chs.mst
[nicurl.msi]
Path=bin\p23\nicurl.msi
Volume=1
ProductCode={1FFA3461-FF9C-4E3A-8152-E531D17BCEFD}
ProductId={1FFA3461-FF9C-4E3A-8152-E531D17BCEFD}
[nicurl64.msi]
Path=bin\p23\nicurl64.msi
Volume=1
ProductCode={7C7517BF-41F0-447F-A61F-AC2A94A0C8A6}
[dep_framework64.msi]
Path=bin\p16\NI_De00\dep_framework64.msi
Volume=1
ProductCode={87AF4692-0A4C-4852-8378-7EBD66CFFF2A}
ProductId={87AF4692-0A4C-4852-8378-7EBD66CFFF2A}
[ni_error_report64.msi]
Path=bin\p14\ni_err64\ni_error_report64.msi
Volume=1
ProductCode={506342C4-1FEC-44D8-B6CD-A0EAE2A61D57}
ProductId={506342C4-1FEC-44D8-B6CD-A0EAE2A61D57}
[NIER_Interface.msi]
Path=bin\p11\NIER_Interface.msi
Volume=1
ProductCode={E0DAF96D-BF67-46CD-87A7-45E7E12A8074}
ProductId={E0DAF96D-BF67-46CD-87A7-45E7E12A8074}
[NIER_Interface64.msi]
Path=bin\p11\NIER_Interface64.msi
Volume=1
ProductCode={07EE79B8-D8C0-4DB5-A88D-1473EF205B99}
[nier_native_installer_64.msi]
Path=bin\p5\nier_native_installer_64.msi
Volume=1
ProductCode={E711747D-55A9-4D77-8742-73EE712F782F}
ProductId={E711747D-55A9-4D77-8742-73EE712F782F}
[LVRT_NBFifo64_2024.msi]
Path=bin\p27\LVRT_00\LVRT_NBFifo64_2024.msi
Volume=1
ProductCode={44F92229-E8D9-4AAC-8262-2F50EE62B2B3}
ProductId={44F92229-E8D9-4AAC-8262-2F50EE62B2B3}
LangXfm0007=bin\p27\LVRT_00\LVRT_NBFifo64_2024_deu.mst
LangXfm0012=bin\p27\LVRT_00\LVRT_NBFifo64_2024_fra.mst
LangXfm0017=bin\p27\LVRT_00\LVRT_NBFifo64_2024_jpn.mst
LangXfm0018=bin\p27\LVRT_00\LVRT_NBFifo64_2024_kor.mst
LangXfm2052=bin\p27\LVRT_00\LVRT_NBFifo64_2024_chs.mst
[logos.msi]
Path=bin\p32\logos.msi
Volume=1
ProductCode={A4BE47D6-DC34-4178-AA11-AC3444963042}
ProductId={A4BE47D6-DC34-4178-AA11-AC3444963042}
LangXfm0007=bin\p32\logos_deu.mst
LangXfm0012=bin\p32\logos_fra.mst
LangXfm0017=bin\p32\logos_jpn.mst
LangXfm0018=bin\p32\logos_kor.mst
LangXfm2052=bin\p32\logos_chs.mst
[logos64.msi]
Path=bin\p32\logos64.msi
Volume=1
ProductCode={02061F25-5B88-4B43-A200-4408442AB259}
LangXfm0007=bin\p32\logos64_deu.mst
LangXfm0012=bin\p32\logos64_fra.mst
LangXfm0017=bin\p32\logos64_jpn.mst
LangXfm0018=bin\p32\logos64_kor.mst
LangXfm2052=bin\p32\logos64_chs.mst
[NIWebServer_LVRTE64.msi]
Path=bin\p17\LabVI00\NIWebServer_LVRTE64.msi
Volume=1
ProductCode={41B080CC-3085-4C2E-88A0-1370947C9E8D}
ProductId={41B080CC-3085-4C2E-88A0-1370947C9E8D}
[MatlabInterface.msi]
Path=bin\p19\MatlabInterface.msi
Volume=1
ProductCode={5DB0AA23-C9F8-4760-9A6E-D8626653B557}
ProductId={5DB0AA23-C9F8-4760-9A6E-D8626653B557}
[MatlabInterface64.msi]
Path=bin\p19\MatlabInterface64.msi
Volume=1
ProductCode={BEA0A726-054E-4EF9-AA2C-2EFFDE3C248B}
[MDFSupport.msi]
Path=bin\p25\MDF\MDFSupport.msi
Volume=1
ProductCode={B5A6E95C-2663-4D51-88C9-1D1B32F81947}
ProductId={B5A6E95C-2663-4D51-88C9-1D1B32F81947}
[mDNSResponder.msi]
Path=bin\p10\mDNSResponder.msi
Volume=1
ProductCode={BE6101F1-17EA-4F39-A3D0-E95F28DEAF36}
ProductId={BE6101F1-17EA-4F39-A3D0-E95F28DEAF36}
[mDNSResponder_W64.msi]
Path=bin\p10\mDNSResponder_W64.msi
Volume=1
ProductCode={4D88D2B5-57E8-4611-A772-35BCDC98EEB3}
[MetaUninstaller.msi]
Path=bin\p0\MU\MetaUninstaller.msi
Volume=1
ProductCode={69CB127F-BB5C-4299-A5ED-FE1F7120AF95}
ProductId={69CB127F-BB5C-4299-A5ED-FE1F7120AF95}
[mkl.msi]
Path=bin\p26\mkl.msi
Volume=1
ProductCode={6A8A28A0-4568-4718-A3E7-F951C191602B}
ProductId={6A8A28A0-4568-4718-A3E7-F951C191602B}
LangXfm0007=bin\p26\mkl_deu.mst
LangXfm0012=bin\p26\mkl_fra.mst
LangXfm0017=bin\p26\mkl_jpn.mst
LangXfm0018=bin\p26\mkl_kor.mst
LangXfm2052=bin\p26\mkl_chs.mst
[mkl64.msi]
Path=bin\p26\mkl64.msi
Volume=1
ProductCode={C8AE1FF1-C898-4171-B03B-94D5E487C2D8}
LangXfm0007=bin\p26\mkl64_deu.mst
LangXfm0012=bin\p26\mkl64_fra.mst
LangXfm0017=bin\p26\mkl64_jpn.mst
LangXfm0018=bin\p26\mkl64_kor.mst
LangXfm2052=bin\p26\mkl64_chs.mst
[mkl.msi<2>]
Path=bin\p29\mkl.msi
Volume=1
ProductCode={A12FB799-41BF-4A9A-98F2-2FE4F333B718}
ProductId={A12FB799-41BF-4A9A-98F2-2FE4F333B718}
LangXfm0007=bin\p29\mkl_deu.mst
LangXfm0012=bin\p29\mkl_fra.mst
LangXfm0017=bin\p29\mkl_jpn.mst
LangXfm0018=bin\p29\mkl_kor.mst
LangXfm2052=bin\p29\mkl_chs.mst
[mkl64.msi<2>]
Path=bin\p29\mkl64.msi
Volume=1
ProductCode={E32B7385-4770-4AED-B9DE-5A079EC82D07}
LangXfm0007=bin\p29\mkl64_deu.mst
LangXfm0012=bin\p29\mkl64_fra.mst
LangXfm0017=bin\p29\mkl64_jpn.mst
LangXfm0018=bin\p29\mkl64_kor.mst
LangXfm2052=bin\p29\mkl64_chs.mst
[MSIProperties.msi]
Path=bin\p15\MetaUtils\MSIProperties.msi
Volume=1
ProductCode={6B2945C0-BA03-4994-AC9D-882F5189916A}
ProductId={6B2945C0-BA03-4994-AC9D-882F5189916A}
[MSIProperties64.msi]
Path=bin\p15\MetaUtils\MSIProperties64.msi
Volume=1
ProductCode={F38CA16E-3A8C-4DB3-869C-6D7D676DCCA1}
[MStudioCW3DGraph.msi]
Path=bin\p35\MStudioCW3DGraph.msi
Volume=1
ProductCode={A9B6FC03-1277-40DF-A475-32389FD27883}
ProductId={A9B6FC03-1277-40DF-A475-32389FD27883}
[VCRTCore.msi]
Path=bin\p3\VCRTCore.msi
Volume=1
ProductCode={55D38C03-ED3A-4351-ADD2-971FFABBEE37}
ProductId={55D38C03-ED3A-4351-ADD2-971FFABBEE37}
[VCRTWrapper32.msi]
Path=bin\p3\VCRTWrapper32.msi
Volume=1
ProductCode={1762CF0C-CC57-407F-B2B3-9A1E1D3FFB86}
[VCRTWrapper64.msi]
Path=bin\p3\VCRTWrapper64.msi
Volume=1
ProductCode={C0E89897-8713-4A77-ABF0-33867DF381A6}
[PythonInterface.msi]
Path=bin\p21\PythonInterface.msi
Volume=1
ProductCode={FFACA5E1-969B-47BA-89BD-B14F603BC66A}
ProductId={FFACA5E1-969B-47BA-89BD-B14F603BC66A}
[PythonInterface64.msi]
Path=bin\p21\PythonInterface64.msi
Volume=1
ProductCode={B77AA011-F231-4AA6-96E6-00D462CA8EDF}
[nisvcloc.msi]
Path=bin\p28\svcloc\nisvcloc.msi
Volume=1
ProductCode={B9E050D3-8BC3-459E-BE16-79711EDD9C7E}
ProductId={B9E050D3-8BC3-459E-BE16-79711EDD9C7E}
LangXfm0007=bin\p28\svcloc\nisvcloc_deu.mst
LangXfm0012=bin\p28\svcloc\nisvcloc_fra.mst
LangXfm0017=bin\p28\svcloc\nisvcloc_jpn.mst
LangXfm0018=bin\p28\svcloc\nisvcloc_kor.mst
LangXfm2052=bin\p28\svcloc\nisvcloc_chs.mst
[NISysLogUtils.msi]
Path=bin\p4\NISys00\NISysLogUtils.msi
Volume=1
ProductCode={40B51053-A9E9-4B0F-A92E-985B6770E80B}
ProductId={40B51053-A9E9-4B0F-A92E-985B6770E80B}
[tdms.msi]
Path=bin\p30\tdms.msi
Volume=1
ProductCode={885A85CD-F005-43B9-B6F1-A59693B788E4}
ProductId={885A85CD-F005-43B9-B6F1-A59693B788E4}
LangXfm0007=bin\p30\tdms_deu.mst
LangXfm0012=bin\p30\tdms_fra.mst
LangXfm0017=bin\p30\tdms_jpn.mst
LangXfm0018=bin\p30\tdms_kor.mst
LangXfm2052=bin\p30\tdms_chs.mst
[tdms64.msi]
Path=bin\p30\tdms64.msi
Volume=1
ProductCode={EA42F380-67DC-406E-9836-91A7B110D780}
LangXfm0007=bin\p30\tdms64_deu.mst
LangXfm0012=bin\p30\tdms64_fra.mst
LangXfm0017=bin\p30\tdms64_jpn.mst
LangXfm0018=bin\p30\tdms64_kor.mst
LangXfm2052=bin\p30\tdms64_chs.mst
[NITraceEngine.msi]
Path=bin\p8\NITraceEngine.msi
Volume=1
ProductCode={5A656240-393B-4579-B9E1-D5B45E75ACEC}
ProductId={5A656240-393B-4579-B9E1-D5B45E75ACEC}
[NITraceEngine64.msi]
Path=bin\p8\NITraceEngine64.msi
Volume=1
ProductCode={3C6FA667-BE0A-4D47-81F1-04CCAA628911}
[openssl_ni_3.msi]
Path=bin\p12\openssl_ni_3.msi
Volume=1
ProductCode={0CEDF192-B35E-450A-966E-6BC87982ADB7}
ProductId={0CEDF192-B35E-450A-966E-6BC87982ADB7}
[openssl_ni_3_x86.msi]
Path=bin\p9\openssl_ni_3_x86.msi
Volume=1
ProductCode={034AEF63-07CE-48F3-BD2A-3DD34D623A38}
ProductId={034AEF63-07CE-48F3-BD2A-3DD34D623A38}
[DotNet480.msi]
Path=bin\p2\DotNet480.msi
Volume=1
ProductCode={2DBD7334-4660-4C6A-B070-67278D05F657}
ProductId={2DBD7334-4660-4C6A-B070-67278D05F657}
[DotNet480_Wrapper.msi]
Path=bin\p2\DotNet480_Wrapper.msi
Volume=1
ProductCode={01035681-6527-4E25-A70C-E008F69301A2}
LangXfm0007=bin\p2\DotNet480_Wrapper_deu.mst
LangXfm0012=bin\p2\DotNet480_Wrapper_fra.mst
LangXfm0017=bin\p2\DotNet480_Wrapper_jpn.mst
LangXfm0018=bin\p2\DotNet480_Wrapper_kor.mst
LangXfm2052=bin\p2\DotNet480_Wrapper_chs.mst
[error_reporting_common.msi]
Path=bin\p6\error_reporting_common.msi
Volume=1
ProductCode={71CD580E-2059-4209-B011-92BA309A0D7D}
ProductId={71CD580E-2059-4209-B011-92BA309A0D7D}
[LogosXT.msi]
Path=bin\p24\LogosXT.msi
Volume=1
ProductCode={57B50CD9-CB54-45B4-909F-9B1F3A0A5C7B}
ProductId={57B50CD9-CB54-45B4-909F-9B1F3A0A5C7B}
[LogosXT64.msi]
Path=bin\p24\LogosXT64.msi
Volume=1
ProductCode={A9D7B3C2-AC6A-4922-9057-C9F4F83F6086}
[niauth.msi]
Path=bin\p22\niauth.msi
Volume=1
ProductCode={3A6E950B-EE71-48A4-BBB1-5503E650AA0B}
ProductId={3A6E950B-EE71-48A4-BBB1-5503E650AA0B}
[niauth64.msi]
Path=bin\p22\niauth64.msi
Volume=1
ProductCode={10F7BBF7-7D4B-485E-BDFA-A47D307D2D81}
[NI_SysStatePub.msi]
Path=bin\p20\NI_SysStatePub.msi
Volume=1
ProductCode={43FDBC22-7F08-4AA5-A54F-819E3F3433FF}
ProductId={43FDBC22-7F08-4AA5-A54F-819E3F3433FF}
[NI_SysStatePub64.msi]
Path=bin\p20\NI_SysStatePub64.msi
Volume=1
ProductCode={29AB17FF-F565-486B-BBFD-94E38B551F50}
[ssl_LV64RTEsupp.msi]
Path=bin\p13\ssl64RTE\ssl_LV64RTEsupp.msi
Volume=1
ProductCode={C96107C8-73C1-457D-861F-C42996ED275D}
ProductId={C96107C8-73C1-457D-861F-C42996ED275D}
[EULADepot2.msi]
Path=bin\p1\EULADepot2.msi
Volume=1
ProductCode={46D14A10-C315-4AA8-AE49-FEC400B93588}
ProductId={46D14A10-C315-4AA8-AE49-FEC400B93588}
[KillBit.msi]
Path=bin\p7\KillBit.msi
Volume=1
ProductCode={64ECB814-3A6A-4E48-9D2F-D6C2EDD725B7}
ProductId={64ECB814-3A6A-4E48-9D2F-D6C2EDD725B7}
[KillBit64.msi]
Path=bin\p7\KillBit64.msi
Volume=1
ProductCode={3BD1EEE5-2B3D-428A-9CAB-4DE4A38070C4}
[dotnetDesktopRuntimeCore.msi]
Path=bin\p34\dotnetDesktopRuntimeCore.msi
Volume=1
ProductCode={4EED8F3B-E578-4698-A8A5-00AB2D190858}
ProductId={4EED8F3B-E578-4698-A8A5-00AB2D190858}
[ni_ssl.msi]
Path=bin\p31\ni_ssl.msi
Volume=1
ProductCode={0D0FADFB-A324-4CCE-94A2-72B994800F20}
ProductId={0D0FADFB-A324-4CCE-94A2-72B994800F20}
LangXfm0007=bin\p31\ni_ssl_deu.mst
LangXfm0012=bin\p31\ni_ssl_fra.mst
LangXfm0017=bin\p31\ni_ssl_jpn.mst
LangXfm0018=bin\p31\ni_ssl_kor.mst
LangXfm2052=bin\p31\ni_ssl_chs.mst
[ni_ssl64.msi]
Path=bin\p31\ni_ssl64.msi
Volume=1
ProductCode={D5B92360-3609-443B-B021-A08497011B0B}
LangXfm0007=bin\p31\ni_ssl64_deu.mst
LangXfm0012=bin\p31\ni_ssl64_fra.mst
LangXfm0017=bin\p31\ni_ssl64_jpn.mst
LangXfm0018=bin\p31\ni_ssl64_kor.mst
LangXfm2052=bin\p31\ni_ssl64_chs.mst
[install.msi]
Path=bin\dp\install.msi
Volume=1
ProductCode={25908D96-AED2-4BC8-AA2D-500898BCD209}
ProductId={25908D96-AED2-4BC8-AA2D-500898BCD209}
[LicenseTypes]
LicenseType2=NIStandardReleased
LicenseType3=Apache20
LicenseType4=Boost
LicenseType5=BSD3Clause
LicenseType6=MatLabBSD
LicenseType7=CryptoPP
LicenseType8=DotNet48
LicenseType9=DotNet60
LicenseType10=FreeType
LicenseType11=IntelSimplified2018
LicenseType12=LGPL
LicenseType13=LLVM
LicenseType14=MARS
LicenseType15=Mesa
LicenseType16=MicrosoftPublicLicense
LicenseType17=MSVC 2015 Runtime
LicenseType18=MSVC 2015-2022 Runtime
LicenseType19=MIT
LicenseType20=MIT-X-YAJL
LicenseType21=MIT-X
LicenseType22=Mozilla20
LicenseType23=NICTA
LicenseType24=OpenSSL
LicenseType25=SIL
LicenseType26=wxWindows
LicenseType27=WordNet21
LicenseType28=zlib
[LicenseType2]
IsDisplayedAlone=0
IsThirdParty=0
IsHideInMetaSuite=0
[LicenseType3]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType4]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType5]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType6]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType7]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType8]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType9]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType10]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType11]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType12]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType13]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType14]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType15]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType16]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType17]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType18]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType19]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType20]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType21]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType22]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType23]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType24]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType25]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType26]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType27]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType28]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[DotNetPreinstall]
DotNet40Preinstall=1
DotNet40Path=bin\p2\ndp48-x86-x64-allos-enu.exe
DotNet40Version=4.8.4115.0
DotNet40ProductCode={01035681-6527-4E25-A70C-E008F69301A2}
[SilentInstallRequirements]
MustAcceptLicenses=1
[MDF]
MDFVersion=24.5.0.49245
HasPatchSupport=0
DevPartSection=install.msi
